### ISSUE TITLE
Error : C_START_SKILL and S_START_COOLTIME on Caalis Toolbox

### ISSUE THREAD

**Issue by Yasukii** [Tera-Shiraneko/lazyrootbeer#1]
![node_2019-07-20_19-25-16](https://user-images.githubusercontent.com/34219032/61581860-394c8800-ab24-11e9-8344-22f1a4388d02.png)

**Comment by Yasukii** [comment]
![TCC_2019-07-20_19-46-42](https://user-images.githubusercontent.com/34219032/61582131-2091a180-ab27-11e9-9497-a40b06606201.png)

**Comment by Yasukii** [comment]
I would appreciate any kinda help, I cant figure it out myself.

**Comment by Tera-Shiraneko** [comment]
Issue is fixed now. Restart your toolbox and everything should work afterwards.
