### ISSUE TITLE
Failed to update index.js

### ISSUE THREAD

**Issue by unlimitedgtx** [Tera-Shiraneko/lazyrootbeer#1]
My error:
Failed to update the following module files:
 - index.js
 - ERROR: https://raw.githubusercontent.com/Tera-Shiraneko/lazyrootbeer/master/index.js
Downloaded file doesn't match hash specified in patch manifest! Possible causes:
   + Incorrect manifest specified by module developer
   + NoPing (if you're using it) has a bug that can fuck up the download

**Comment by Tera-Shiraneko** [comment]
Problem should be solved now somehow my manifest generator was fucked.
