### ISSUE TITLE
No brooche

### ISSUE THREAD

**Issue by unlimitedgtx** [Tera-Shiraneko/lazyrootbeer#2]
Doesn't work for me. I tried my lancer and my ninja. And for other classes too.
I press my ulti, but nothing happend. it doesnt use my equipped brooche. I have the Quatrefoil Brooch. But in ur index, there is only the Marrow Brooch, and if i want to change/add my one, and i start the game, it resets the file.

**Comment by Tera-Shiraneko** [comment]
There should be all ID´s in the index id : [51028, 98406, 98405, 98404],  and you have to be infight that it will use the brooch and rootbeer automatic + you need to use the skill in the skills file or add them yourself to make this work.

**Comment by unlimitedgtx** [comment]
LOL, still doesnt work. I add my skill ID's in the skill fill, I was infight, but no, doenst work.

**Comment by Tera-Shiraneko** [comment]
Are you playing on eu or na.

**Comment by unlimitedgtx** [comment]
Eu

**Comment by Tera-Shiraneko** [comment]
.  And 51011 is id for non bound quatrefoil brooch and its na datacenter btw so this cant be right that you play on eu.

**Comment by Tera-Shiraneko** [comment]
O wait na and eu eng id is same

**Comment by Tera-Shiraneko** [comment]
98406 is the  bound quatrefoil brooch id which is already in index. Dont know why its not working for you its working fine for me.

**Comment by unlimitedgtx** [comment]
I looked in https://teralore.com and searched the ID's for my skills. But i'm playing on eu

**Comment by Tera-Shiraneko** [comment]
Which proxy are you using?

**Comment by Tera-Shiraneko** [comment]
Most of the skill ids in teralore are wrong.

**Comment by Tera-Shiraneko** [comment]
Try /8 au debug instead then use desire skill it will print the skill id in console after that.

**Comment by Tera-Shiraneko** [comment]
And if you are using pinkies proxy it wont work at all cause I used tera game state instead of the old dispatch so the module only works with caalis proxy.

**Comment by unlimitedgtx** [comment]
i use the newest one from caali proxy, downloaded it yesterday again. where can i find the actually id's?

au debug set it to true, press skill and then?

**Comment by Tera-Shiraneko** [comment]
Add the skill id in the skills file to the right class.

**Comment by unlimitedgtx** [comment]
yeah i did on my valk

**Comment by unlimitedgtx** [comment]
wait.. i will try

**Comment by Tera-Shiraneko** [comment]
"glaiver": {
 	"_comment" : "VALK",
	"useBroochOn" : [],
	"useRootBeerOn" : [],
	"useOutofCombat" : false,
	"delay" : 0
	},
Just add skill id from console between the []

**Comment by unlimitedgtx** [comment]
Finally worked! The ID was the Problem. I'm really grateful! Thanks.
