### ISSUE TITLE
question

### ISSUE THREAD

**Issue by magnets8** [Tera-Shiraneko/lazyrootbeer#2]
hi.. im having a problem by using this mod with my archer. at the moment I cast windsong the brooch and rootbeer dont pop up. this only happen with windsong with the advance skill gale, cause in other alter without that skill the mod works fine.

**Comment by Tera-Shiraneko** [comment]
Type /8 lazybeer debug and use windsong with the advance skill option.
After that type /8 lazybeer config and change the id with the one from the console.
Should work afterwards.

The hint is also written in the readme btw [If you unlock an skill option for an already added skill it's possible that the id will change.]
