### ISSUE TITLE
Rootbeer sometimes not activating for some reason

### ISSUE THREAD

**Issue by Zezo12345** [Tera-Shiraneko/lazyrootbeer#2]
Sometimes the rootbeer doesn't activate after gunner weapon system and sometimes it does, dunno what i could be doing wrong, maybe weapon system has lower cooldown than rootbeer while in party and buffed? I noticed this in Gossamer vault sometimes.

**Comment by Tera-Shiraneko** [comment]
Yes depending on your cdr values this is possible. Have you tried casting weapon system 2-3 secs after its ready again. Should work this way if I dont miss calculated anything.

**Comment by Tera-Shiraneko** [comment]
On the other side I can tell for sure that the module is working exactly like it should so it must be lower cd value of your trigger skill than rootbeer.

**Comment by Tera-Shiraneko** [comment]
But you can easily test this yourself activate the skill to trigger rootbeer and do it again after rootbeer is ready. If it get triggered the problem is just that your skill is ready faster than the rootbeer cd.

**Comment by Zezo12345** [comment]
Are you able to make an option to avoid those conditions and activate rootbeer when off cd and during weapon system when weapon system has 20 more duration or something?

**Comment by Tera-Shiraneko** [comment]
Sure it is possible but I am not gonna add this just for one class. You can use brooch/rootbeer normally at the start if the fight and use module with some sec delay for infight.
